### ISSUE TITLE
[Feature request]: Rich Soil Farmland (from Farmer's Delight)

### ISSUE THREAD

**Issue by steve-the-player** [ArkoSammy12/Aquifer#1]
![2024-01-15_13 25 52](https://github.com/ArkoSammy12/Aquifer/assets/61434698/0a0e9165-c14a-4696-b20b-d84da86d8392)

**Comment by ArkoSammy12** [comment]
@steve-the-player I have posted a new [release](https://modrinth.com/mod/aquifer/version/0.0.2-1.19.4+) of the mod that adds this feature. Thank you for suggesting this feature. Make sure to report any bugs or issues you may have :D
